
@endpoint = https://bx952q6y2g.execute-api.us-east-1.amazonaws.com/prod
GET {{endpoint}}/hello
###

GET {{endpoint}}/spaces
###

GET {{endpoint}}/spaces?spaceId=014dcd94-2151-43a6-a5a8-35950f4a8a17
###

GET {{endpoint}}/spaces?location=Osp
###

GET {{endpoint}}/spaces
###

POST {{endpoint}}/spaces
Content-Type: application/json

{
    "location":"Osp",
    "name":"second best location"
}
###

PUT {{endpoint}}/spaces?spaceId=89855466-d2f1-4e7d-abd0-3711e10b451c
Content-Type: application/json

{
    "location":"Osp",
    "name":"new second best location"
}
###